export enum GetUsersActionTypes {
  GET_USERS_REQUEST = 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE = 'GET_USERS_FAILURE',
};

export enum CreateUserActionTypes {
  CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST',
  CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS',
  CREATE_USERS_FAILURE = 'CREATE_USERS_FAILURE',
};